"""empty message

Revision ID: 4b26091adc9d
Revises: bc9dc121501e
Create Date: 2020-05-24 17:36:47.153297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b26091adc9d'
down_revision = 'bc9dc121501e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('color', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
